### ISSUE TITLE
Base word

### ISSUE THREAD

**Issue by Coolnesss** [TurkuNLP/Finnish-dep-parser#19]
Hey,

Is it possible to use the parser to get the base word of a stemmed word, e.g

jomotus -> jomottaa
särky -> särkeä 

etc.

Thanks

**Comment by jmnybl** [comment]
Hi @Coolnesss ,

To some extent yes. You can try to run the Omorfi morphological analyzer using command 'python omorfi_pos.py -o -i' and try to feed in these words. Sometimes it outputs the derivational analyses, but unfortunately sometimes not:

token> opettaja
opettaa --- V Der_ja N Sg Nom cap
opettaja --- N Sg Nom cap

token> heittely
heitellä --- V Der_u Sg Nom cap
heittely --- N Sg Nom cap

token> särky
särky --- N Sg Nom cap

You can also try the actual Omorfi repo (https://github.com/flammie/omorfi) to get the latest Omorfi release. It has better coverage of words but at some point derivations were partly dropped from the newer analyzer so the derivation coverage was actually worse. I don't know what the status is now, you can ask there if needed.

**Comment by flammie** [comment]
@jmnybl is right, the automatic derivations were dropped from omorfi in favour of manually verifying and adding new lexical entries, for most applications and end users this was the path of least resistance. However, now that many more analysis pipelines support finer ways to hide creative derivations from users who don't understand them, the derivations are probably slowly getting added back in, but they are being added manually per paradigm (inflection class) so it'll take a while until coverage of that mechanism is back to old values. 

E.g. adding -y derivations to the inflection class of särkeä is quite fast and easy <https://github.com/flammie/omorfi/commit/53a4ff10fde5b09f67ca1f55396c71c86fbf492e>  but it only reaches three lexemes: särkeä : särky, nylkeä : nylky and sylkeä : sylky.
