### ISSUE TITLE
UDv1 and UDv2 trees

### ISSUE THREAD

**Issue by pkolachi** [TurkuNLP/Finnish-dep-parser#25]
I managed to run the current version of the Finnish parser from github.  The master branch seems to return UDv1 trees. 
When I try to run the code in the ud_v2 branch, I get the following error:
Exception in thread "main" java.lang.RuntimeException: java.io.InvalidClassException: marmot.morph.MorphModel; local class incompatible: stream classdesc serialVersionUID = 1, local class serialVersionUID = 2

I am wondering if UDv1 is the current version or if there is a way to get UDv2 trees as well. Thanks.

**Comment by jmnybl** [comment]
UDv2 is supported in our new pipeline at https://turkunlp.github.io/Turku-neural-parser-pipeline/ with pretrained models for more than 50 languages and substantially better accuracy in all layers of prediction.
