### ISSUE TITLE
Outdated marmot model url in install script

### ISSUE THREAD

**Issue by aajarven** [TurkuNLP/Finnish-dep-parser#26]
The [install script](https://github.com/TurkuNLP/Finnish-dep-parser/blob/fc8511cd16541e3b07072352d5801b54a5c05cf3/install.sh#L91) tries to get the marmot model from http://bionlp-www.utu.fi/Finnish-parser-models/UD.1/fin_model.marmot, but that URL is no longer functional. 
 
Is the old model still available somewhere else? If so, the url could be updated.

**Comment by fginter** [comment]
Hi

We don't maintain this version of the parser anymore and have moved on to http://turkunlp.org/Turku-neural-parser-pipeline/ which is accuracy-wise far superior.  Other options you might have for a good Finnish parser is "trankit". Nevertheless, the model you asked for I now moved to http://epsilon-it.utu.fi/Finnish-parser-models/UD.1/

All the best

Filip
